[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/customers"
  to = "/.netlify/functions/customers"
  status = 200

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/api/lookup"
  to = "/.netlify/functions/lookup"
  status = 200
